module.exports = {
    solicitarLoteMovimentacao :(req,res,next) =>{},
    listarLoteMovimentacao:(req,res,next) =>{},
    visualizarLoteMovimentacao:(req,res,next) =>{},
    realizarBaixaLoteMovimentacao:(req,res,next) =>{},
    cancelarLoteMovimentacao:(req,res,next) =>{},
    baixarArquivoLayoutLote:(req,res,next) =>{},
    solicitarImportacaoLoteMovimentacao:(req,res,next) =>{},
    listarRetornoLoteMovimentacao:(req,res,next) =>{},
    visualizarRetornoLoteMovimentacao:(req,res,next) =>{},
    cancelarRetornoLoteMovimentacao:(req,res,next) =>{},
    baixarArquivoRetornoLoteMovimentacao:(req,res,next) =>{},
    visualizarRelatorioPdfBeneficiariosAtivo:(req,res,next) =>{},
    visualizarExcelBeneficiariosPorOperadora:(req,res,next) =>{},
    visualizarRelatorioBeneficiariosPorOperadora:(req,res,next) =>{},
}